### ISSUE TITLE
Add an "ARROW" type to the token types

### ISSUE THREAD

**Issue by PolyPik** [NightlyCommit/twig-lexer#7]
TwigPHP includes an [ARROW_TYPE](https://github.com/twigphp/Twig/blob/1190d3d42031d0484f421bb5dc2e8759e786caa4/src/Token.php#L39) as one of its token types.

**Comment by ericmorand** [comment]
Thanks a lot for the PR. It's merged. I'll release 0.4.0 as soon as I'm back for holidays - in a week or so.
